name: Deploy from Directus

on:
  # publish blog using webhook
  repository_dispatch:
    types: [dokku_rebuild]

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
    - name: dokku ps:rebuild
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: ps:rebuild web
